Fix randomly failing test test_tags_allocations_for_spans (#181)
This test would fail when running just its containing file on Python 3 with:

```
>       assert span.tags["allocations"] > 0
E       assert 0 > 0
```

Turns out `objtrace.enable()` needs calling to ensure it does track.

There's no easy way of making a test fixture that resets the enabled/disabled state at the end of it, but there probably isn't a need anyway as `install()` does `objtrace.enable()` anyway.