Stop CoreAgentSocketThread after every test (#404)
Should prevent random errors which seem to happen fairly frequently in Travis runs like:

```
______________________________ test_launch_error _______________________________

caplog = <_pytest.logging.LogCaptureFixture object at 0x7f44d4c65f60>

core_agent_manager = <scout_apm.core.core_agent_manager.CoreAgentManager object at 0x7f44d4c65940>

    def test_launch_error(caplog, core_agent_manager):
        caplog.set_level(logging.ERROR)
        exception = ValueError("Hello Fail")
        with mock.patch(
            "scout_apm.core.core_agent_manager.CoreAgentManager.agent_binary",
            side_effect=exception,
        ):
            result = core_agent_manager.launch()

        assert not result
        assert not is_running(core_agent_manager)
>       assert caplog.record_tuples == [
            ("scout_apm.core.core_agent_manager", logging.ERROR, "Error running Core Agent")
        ]
E       assert [('scout_apm.... Core Agent')] == [('scout_apm.... Core Agent')]
E         At index 0 diff: ('scout_apm.core.socket', 10, 'CoreAgentSocket attempt 2, connecting to /tmp/scout_apm_core/scout_apm_core-v1.2.4-x86_64-unknown-linux-gnu/scout-agent.sock, PID: 4215, Thread: <CoreAgentSocket(Thread-1, started daemon 139933644363520)>') != ('scout_apm.core.core_agent_manager', 40, 'Error running Core Agent')
E         Left contains 2 more items, first extra item: ('scout_apm.core.socket', 10, "CoreAgentSocket connection error: FileNotFoundError(2, 'No such file or directory')")
E         Use -v to get the full diff
```

Also catch any `Full` exceptions when trying to `Queue.put()` to stop, since they are only there to unblock a waiting consumer which will happen when the queue is empty.