Attempt to fix timing bug on Travis
Have been seeing rare failures on Travis like:

```
=================================== FAILURES ===================================
_ test_track_amazon_request_queue_time_valid[Root=1-{start_time}-12456789abcdef012345678;CalledFrom=app] _
header_value = 'Root=1-{start_time}-12456789abcdef012345678;CalledFrom=app'
tracked_request = <TrackedRequest(request_id='req-ca2b1c89-b2b7-4f9a-b5a8-ffbde626c511', tags={'scout.queue_time_ns': 1999785984})>
    @pytest.mark.parametrize(
        "header_value",
        [
            "Root=1-{start_time}-12456789abcdef012345678",
            "Root=1-{start_time}-12456789abcdef012345678;CalledFrom=app",
            "Self=1-{start_time}-12456789abcdef012345678",
            "Self=1-{start_time}-12456789abcdef012345678;Root=1-123-abcdef012345678912345678",  # noqa: E501
            "Self=1-{start_time}-12456789abcdef012345678;Root=1-123-abcdef012345678912345678;CalledFrom=app",  # noqa: E501
        ],
    )
    def test_track_amazon_request_queue_time_valid(header_value, tracked_request):
        start_time = int(datetime_to_timestamp(dt.datetime.utcnow()) - 2)

        result = track_amazon_request_queue_time(
            header_value.format(start_time=start_time), tracked_request
        )

        assert result is True
        queue_time_ns = tracked_request.tags["scout.queue_time_ns"]
        # Upper bound assumes we didn't take more than 2s to run this test...
>       assert queue_time_ns >= 2000000000 and queue_time_ns < 4000000000
E       assert (1999785984 >= 2000000000)
```

2 seconds taking just less than 2 seconds, in nanoseconds.

Although they're rare, btween the mulpitle tests using the pattern and mutliple environmetns, it appears in ~1/3 of test runs at the moment.

This is an attempt to fix it by changing the failing pattern to potentially avoid floating point rounding errors.